version: "3.1"
services:
  react:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: React_brook_store_container
    volumes:
      - ./src:/React_brook_store/src:ro
    ports:
      - "3050:3050"
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    # volumes:
    #     - ./Care_Frontend/build:/usr/share/nginx/html:ro
    ports:
      - 85:80
    restart: always
